/*
 * melo_browser_jsonrpc.h: Browser base JSON-RPC interface
 *
 * Copyright (C) 2016 Alexandre Dilly <dillya@sparod.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

#ifndef __MELO_BROWSER_JSONRPC_H__
#define __MELO_BROWSER_JSONRPC_H__

#include "melo_browser.h"
#include "melo_jsonrpc.h"

/**
 * MeloBrowserJSONRPCInfoFields:
 * @MELO_BROWSER_JSONRPC_INFO_FIELDS_NONE: get nothing
 * @MELO_BROWSER_JSONRPC_INFO_FIELDS_NAME: get browser display name
 * @MELO_BROWSER_JSONRPC_INFO_FIELDS_DESCRIPTION: get browser description
 * @MELO_BROWSER_JSONRPC_INFO_FIELDS_SEARCH: get search capabilities
 * @MELO_BROWSER_JSONRPC_INFO_FIELDS_GO: get 'go' capabilities
 * @MELO_BROWSER_JSONRPC_INFO_FIELDS_TAGS: get tags caching mode capabilities
 * @MELO_BROWSER_JSONRPC_INFO_FIELDS_FULL: get everything
 *
 * MeloBrowserJSONRPCInfoFields is a bit field to list which details must be
 * filled in the #JsonObject generated by melo_browser_jsonrpc_info_to_object()
 * from a #MeloBrowserInfo.
 */
typedef enum {
  MELO_BROWSER_JSONRPC_INFO_FIELDS_NONE = 0,
  MELO_BROWSER_JSONRPC_INFO_FIELDS_NAME = 1,
  MELO_BROWSER_JSONRPC_INFO_FIELDS_DESCRIPTION = 2,
  MELO_BROWSER_JSONRPC_INFO_FIELDS_SEARCH = 4,
  MELO_BROWSER_JSONRPC_INFO_FIELDS_GO = 8,
  MELO_BROWSER_JSONRPC_INFO_FIELDS_TAGS = 16,

  MELO_BROWSER_JSONRPC_INFO_FIELDS_FULL = ~0,
} MeloBrowserJSONRPCInfoFields;

MeloBrowserJSONRPCInfoFields melo_browser_jsonrpc_get_info_fields (
                                                             JsonObject *obj,
                                                             const gchar *name);
JsonObject *melo_browser_jsonrpc_info_to_object (
                                           const gchar *id,
                                           const MeloBrowserInfo *info,
                                           MeloBrowserJSONRPCInfoFields fields);

/* JSON-RPC methods */
void melo_browser_jsonrpc_register_methods (void);
void melo_browser_jsonrpc_unregister_methods (void);

#endif /* __MELO_BROWSER_JSONRPC_H__ */
